### ISSUE TITLE
Ambiguous redirect error

### ISSUE THREAD

**Issue by tarheels100** [MarkLodato/git-reparent#2]
On Windows 7, I got the following error:
`git-reparent: line 80: 0: ambiguous redirect`

I was able to resolve the problem by adding double quotes around $msg_file on line 80 to yield:
`new_head="$(eval "git commit-tree HEAD: $parent_flags" '< "$msg_file"')" || \`

Presumably spaces in the file path were to blame.

**Comment by MarkLodato** [comment]
Thanks for reporting!

**Comment by tarheels100** [comment]
No problem.  Thank you for providing this script.  It helped me get out of a tight situation!
